[versions]
agp = "9.0.0"
kotlin = "2.3.0"
compose = "1.10.1"
compose-compiler = "1.5.4"
compose-runtime = "1.10.0"
compose-material3 = "1.4.0"
androidx-activityCompose = "1.12.2"
androidx-graphicsShapes = "1.1.0"
coroutinesVersion = "1.10.2"
dateTimeVersion = "0.7.1"
kotlinx-serialization = "1.9.0"
koin = "4.1.1"
ktor = "3.3.3"
material-icons-extended = "1.7.8"
room = "2.8.4"
sqlite = "2.6.2"
lifecycleViewmodelCompose = "2.10.0"
datastore = "1.2.0"
ksp = "2.3.2"
googlePlayServices = "21.3.0"
androidx-work = "2.11.0"
navigationVersion = "2.9.6"
skie = "0.10.9"
kmpObservableViewModel = "1.0.0-BETA-9"

[libraries]
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesVersion" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "dateTimeVersion" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-runtime" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }
androidx-graphics-shapes = { module = "androidx.graphics:graphics-shapes", version.ref = "androidx-graphicsShapes" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-common = { module = "androidx.room:room-common", version.ref = "room" }
room-common-iossimulatorarm64 = { module = "androidx.room:room-common-iossimulatorarm64", version.ref = "room" }
room-common-iosx64 = { module = "androidx.room:room-common-iosx64", version.ref = "room" }
room-common-iosarm64 = { module = "androidx.room:room-common-iosarm64", version.ref = "room" }
room-runtime-iossimulatorarm64 = { module = "androidx.room:room-runtime-iossimulatorarm64", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "googlePlayServices" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationVersion" }
kmp-observable-viewmodel = { group = "com.rickclephas.kmp", name = "kmp-observableviewmodel-core", version.ref = "kmpObservableViewModel" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }
